version: '2'

services:
  apache:
    build: ./docker/apache
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./:/var/www/html

  php:
    build: ./docker/php
    links:
      - mysql
    volumes:
      - ./:/var/www/html

  mysql:
    build: ./docker/mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 127.0.0.1:6446:3306
    volumes:
      - /var/lib/mysql
